# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects unused assignments
    - staticcheck   # Advanced go vet
    - unused        # Checks for unused constants, variables, functions
    - typecheck     # Type checks
    - gofmt         # Checks code is formatted
    - goimports     # Checks imports are formatted
    - misspell      # Finds commonly misspelled words
    - gosec         # Security problems
    - bodyclose     # HTTP response body is closed
    - noctx         # HTTP requests should use context
    - sqlclosecheck # SQL rows/statements are closed
    - rowserrcheck  # Checks if Err of rows is checked
  disable:
    - gocritic      # Too strict for now
    - revive        # Too strict for now  
    - errorlint     # Too strict for now
    - exhaustive    # Too strict for now
    - exportloopref # Deprecated
    - gochecknoinits # Too strict for now
    - goconst       # Too strict for now
    - godot         # Too strict for now
    - gofumpt       # Too strict for now
    - goprintffuncname # Too strict for now
    - nilerr        # Too strict for now
    - nlreturn      # Too strict for now
    - nolintlint    # Too strict for now
    - prealloc      # Too strict for now
    - predeclared   # Too strict for now
    - unconvert     # Too strict for now
    - unparam       # Too strict for now
    - whitespace    # Too strict for now
    - errname       # Too strict for now

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Too strict

  govet:
    check-shadowing: false  # Too strict
    enable-all: false  # Too strict

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/stpatrick2016/flibusta_kindle_bot

  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand)

  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gochecknoinits
        - errcheck
        - gosec
        - dupl

    # Exclude known false positives
    - text: "G404: Use of weak random number generator"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
