# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"
  
  status:
    project:
      default:
        target: 60%              # Target coverage
        threshold: 2%            # Allow 2% decrease
        if_ci_failed: error
        
    patch:
      default:
        target: 70%              # New code should have higher coverage
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "**/*_test.go"
  - "**/mocks/**"
  - "**/testdata/**"
  - "cmd/**"                     # Main files usually not tested

github_checks:
  annotations: true
